### ISSUE TITLE
Argument validations not compatible with dry-initializer

### ISSUE THREAD

**Issue by BensonCasey7** [jonspalmer/view_component_storybook#100]
Our codebase utilizes [dry-initializer-rails](https://github.com/nepalez/dry-initializer-rails) instead of writing typical `def initialize` methods. Due to this fact, all of our stories fail validations because the arguments are considered unexpected.

I'm curious to hear thoughts on either making the validations more flexible or adding a config option to ignore validations when creating stories.

**Comment by tmaier** [comment]
This is a duplicate of #17 - or of dry-rb/dry-initializer#88 to be precise.

@jonspalmer has submitted a pull request against dry-initializer, which is sitting there unmerged.
Maybe you can support on that side to get this working

**Comment by jonspalmer** [comment]
dry-initializer has a new version which we hope will address this problem without changes in this gem. Please check it out and confirm one way or the other. https://github.com/dry-rb/dry-initializer/releases/tag/v3.1.0

**Comment by jonspalmer** [comment]
The dry-initializer change didn't do the trick but new changes in #112 should fix the issues with dry-initializer. Please test and confirm. I'll cut a release once others have validated.

**Comment by BensonCasey7** [comment]
@jonspalmer Just tested and that appears to have fixed it!

**Comment by jonspalmer** [comment]
release v0.11.0 includes this fix
