### ISSUE TITLE
adding control to slots not working properly

### ISSUE THREAD

**Issue by ariesandrada** [jonspalmer/view_component_storybook#105]
I'm using view_component 2.43.1 and view_component_storybook 0.10.1

Here is my sample code:

```
class ExampleModule::ExampleComponentStories < ViewComponent::Storybook::Stories
  story :example_slots do
    example_slot(
      example_text: text('example text 1')
    ).content(text('example content 1'))
  end
end
```

where `example_slot` is a collection. When I try to run `rake view_component_storybook:write_stories_json`, it gives me an error `Validation failed: Param can't be blank`. I traced it back to the slot story config control for `example_text` not being assigned a param.

Anyway, I tried going around this issue by manually assigning a param to the control by doing `example_text: text('example text 1').param('example_slot1__example_text')`. This made the rake task complete successfully. However, changing the value of the control doesn't reflect on the rendered component.  I traced this back to the text config param being appended by a prefix `example_slot1__example_slot1__example_text`.

My current workaround is to generate the json files with the `param` method call and then remove the `param` method call when I run storybook.

Let me know if you need more information. Thanks!

**Comment by jonspalmer** [comment]
just getting back to this. I'm going to need to spend a bit if time walking through the use case and the PR.
