### ISSUE TITLE
Add controls to component slots

### ISSUE THREAD

**Issue by manuelpuyol** [jonspalmer/view_component_storybook#11]
Some more complex components use [Slots](https://github.com/github/view_component#slots-experimental) which also receive parameters.
It'd be good to have a way to add controls for those parameters

**Comment by jonspalmer** [comment]
I like the idea. What kind of API would you have in mind?

**Comment by manuelpuyol** [comment]
I imagine something like

```rb
story(:some_story) do
  controls do
    some_attribute 1
    slot_name.other_attribute 2
  end
end
```

**Comment by jonspalmer** [comment]
Do you have any "real world" examples of components with slots we'd like to write stories for. Trying to understand what we're trying to do. Are there examples from Primer that might be discussion points?

**Comment by manuelpuyol** [comment]
Sure!
We have a `DetailsComponent` where its button have some props which change how the button is rendered.
Here you can see its stories https://github.com/primer/view_components/blob/main/stories/primer/details_component_stories.rb
We had to add multiple stories `details`, `custom_button` and `without_button` which could have been covered with knobs in a single story

**Comment by jonspalmer** [comment]
Looks interesting. What controls would you expect to have in storybook to manipulate those stories and how would you expect to plumb them into to the Ruby api?

**Comment by manuelpuyol** [comment]
Closing for now since slots API is changing a lot :)

**Comment by strika** [comment]
Since ViewComponent now has a new version of slots (v2), do you think it's time to reconsider slots support?

**Comment by jonspalmer** [comment]
See #48 for further conversation on the right API for slots
