### ISSUE TITLE
Script tags included in the layout don't get executed

### ISSUE THREAD

**Issue by charle692** [jonspalmer/view_component_storybook#13]
I'm currently attempting to use view_component_storybook to preview our view_components into our existing storybook setup. Everything works as expected except for one thing. 

If you include any script tags into your storybook_preview layout, for whatever reason it does not get executed. 

I took your https://github.com/jonspalmer/view_component_storybook_example to verify that it was not specific to our application and I was able to reproduce the issue. 

If you modify **storybook_preview.html.erb** to look like so:
```
<!DOCTYPE html>
<html>
<head>
  <title>ActionView::Component Storybook Preview</title>
  <script>console.log("hello world!")</script>
</head>

<body>
<%= yield %>

</body>
</html>
```

The hello world code will never run even though I can see it in the DOM. 

![image](https://user-images.githubusercontent.com/5891054/92964464-2096e400-f442-11ea-82bd-c25b34a7d9b3.png)

Our components are dependent on JavaScript to load in styles and logic which I can't seem to get working. Is there another way to include JS into a preview?

I tried putting the script tags in [preview-head.html](https://storybook.js.org/docs/react/configure/story-rendering#adding-to-head) but since our tags are server side generated this isn't really a solution.

If there's anything that I can do to help debug further or if you need someone to implement logic to make this possible let me know.

**Comment by jonspalmer** [comment]
Thanks for reporting this issue. It's important that we support this use case. I was thinking about it but hadn't proved it out one way or the other. I think the right place to support this is on the Storybook side where we can find script tags in the component html and inject them into the page. Do you think that approach would work here?

**Comment by jonspalmer** [comment]
Supporting this requires changes to storybook server. I've added that here https://github.com/storybookjs/storybook/pull/12522. Once we've merged that PR it should be testable in a Storybook 6.1 alpha release.

**Comment by charle692** [comment]
Sorry about the late reply, if we can do as you suggested on the storybook side and hoist script tags into the page that would work perfectly! Thanks so much for the quickly reply, and all that work you have done on this project and storybook itself!

I'll follow along in the PR and once it's merged and released I'll pull it down and test :).

**Comment by jonspalmer** [comment]
PR is merged. Any version of Storybook 6.1 greater than 6.1.0-alpha.12 should work to test this out.

**Comment by charle692** [comment]
Finally got to testing this. Pulled down the latest alpha and can confirm that scripts are getting loaded properly. Thank you so much for taking the time to address this.
