### ISSUE TITLE
Exception: Not an ActiveModel-compatible object. It must implement :to_partial_path.:

### ISSUE THREAD

**Issue by robzolkos** [jonspalmer/view_component_storybook#16]
I have set things up as per the README (and looked at the demo app too).  

I am getting an exception when rendering my first component.

<img width="634" alt="ss1" src="https://user-images.githubusercontent.com/290616/94933827-ed6fcf80-0498-11eb-86af-8520eaf3d994.png">

The exception in the Rails log is

```
ArgumentError - '#<AvatarRoundedComponent:0x00007f8d79ba68d8 @initials="JB", @bg_color="tw-bg-gray-200", @fg_color="tw-text-gray-600">' is not an ActiveModel-compatible object. It must implement :to_partial_path.:
```

My story is defined as such

```
class AvatarRoundedComponentStories < ViewComponent::Storybook::Stories
  layout "storybook_preview"

  story(:with_initials) do
    controls do
      text(:initials, 'JB')
    end
  end
end
```

Generated JSON story is 

```
{
  "title": "Avatar Rounded Component",
  "stories": [
    {
      "name": "with_initials",
      "parameters": {
        "server": {
          "id": "avatar_rounded_component/with_initials"
        }
      },
      "args": {
        "initials": "JB"
      },
      "argTypes": {
        "initials": {
          "control": {
            "type": "text"
          },
          "name": "Initials"
        }
      }
    }
  ]
}
```

The request to the Rails server is 

```
Started GET "/rails/stories/avatar_rounded_component/with_initials?initials=JB" for ::1 at 2020-10-02 10:22:09 -0400
Processing by ViewComponent::Storybook::StoriesController#show as */*
  Parameters: {"initials"=>"JB", "stories"=>"avatar_rounded_component", "story"=>"with_initials"}
```

```
view_component (2.19.1)
view_component_storybook (0.6.0)

storybook 6.0.22
```

I'm almost certainly doing something wrong but 🤷🏻 can't seem to find the issue.

**Comment by robzolkos** [comment]
I've narrowed this down to my inclusion of `config.view_component.render_monkey_patch_enabled = false` in my `config/application.rb` file in order to use `render_component` (as I also have WickedPDF gem installed)

I'm using Rails 6.0.3.3.

When I comment out the line above it works.

**Comment by robzolkos** [comment]
I think I've narrows it down to the [show template](https://github.com/jonspalmer/view_component_storybook/blob/master/app/views/view_component/storybook/stories/show.html.erb#L1) in the engine

which uses `render`  

`<%= render(@component, &@content_block)%>`

(when the monkey_patch is disabled one needs to use `render_component`)

`<%= render_component(@component, &@content_block)%>`

**Comment by jonspalmer** [comment]
This feels awfully like [this problem](https://github.com/github/view_component/issues/332) which really resolves to a problem with WickedPdf. I'd be open to considering fixes here but I'm also keen not to make changes here that will complicate the Rails 6.1 support especially for a problem that really lies elsewhere. Thoughts?

**Comment by robzolkos** [comment]
Totally understand.  I'll be solving this by removing wickedpdf from my project.
