### ISSUE TITLE
Make ControlConfig#component_params customizable

### ISSUE THREAD

**Issue by nicolas-brousse** [jonspalmer/view_component_storybook#17]
I'm currently trying `view_component_storybook` on a project. It look really interesting.

I notice some issues. One of them is about the component params detection.

In our project we use some concerns on component and sometimes we haven't the `#initialize` method present. This raise and `ActiveModel::ValidationError` on `param` field.

On my current tests I overwrite [the following method](https://github.com/jonspalmer/view_component_storybook/blob/00a80b73f4ccda13cb2d8ed75ce7f4d864a72ea9/lib/view_component/storybook/controls/control_config.rb#L33):
```rb
# https://github.com/jonspalmer/view_component_storybook/blob/00a80b73f4ccda13cb2d8ed75ce7f4d864a72ea9/lib/view_component/storybook/controls/control_config.rb#L33

def component_params
  # @component_params ||= component && component.instance_method(:initialize).parameters.map(&:last)          
  @component_params ||= component && component._default_attributes.keys.map(&:to_sym)
end
```

I think it could be nice to have the possibility in the component stories file to set the params list.

**Comment by jonspalmer** [comment]
Happy to consider a PR with has test cases demonstrating the problem and with the fix.

One question where does `_default_attributes` come from?

**Comment by nicolas-brousse** [comment]
In the current example we use [`ActiveModel::Attributes`](https://github.com/rails/rails/blob/fe76a95b0d252a2d7c25e69498b720c96b243ea2/activemodel/lib/active_model/attributes.rb#L15]

**Comment by nicolas-brousse** [comment]
I don't really have time these days. But I think I'll have some at end of the month.

**Comment by jonspalmer** [comment]
@nicolas-brousse see #20 for a PR that is adding a bit more flexibility to the param parsing. Perhaps that provides some inspiration for the fix (or maybe it fixes it outright?). One note - we can assume the including of `ActiveModel::Attributes` in all components so the change you have above isn't going to work.

**Comment by tmaier** [comment]
Same issue applies when one uses `dry-initializer` gem with components.

I would be already happy, if one could just skip this validation...

**Comment by jonspalmer** [comment]
The way components get instantiated has changes significantly with supporting a new, more explicit `constructor` api. Along with it the validation has changed a lot too. It would be great to test these changes against your use cases and see if the situation is improved

**Comment by nicolas-brousse** [comment]
Hi @jonspalmer thanks for your updates.

I did a quick test on a project, and I've an error, but not sure why.

FYI I use [`dry-initializer` gem](https://dry-rb.org/gems/dry-initializer/3.0/) on our latest project.

I test with the following:

```rb
# frozen_string_literal: true

class IconComponent < ViewComponent::Base
  extend Dry::Initializer

  option :icon
  option :extra_classes, optional: true

  def call
    tag.svg(class: classes) do
      tag :use, "xlink:href": "#icon-#{icon}"
    end
  end

  private

  def classes
    class_names("icon", "icon-#{icon}", extra_classes)
  end
end
```

```rb
class IconComponentStories < ViewComponent::Storybook::Stories
  story :default do
    constructor(
      icon: text(:key)
    )
  end
end
```
This stories file failed on rake task execution
```
ViewComponent::Storybook::Stories::ValidationError: IconComponentStories invalid: (Story configs 'default' is invalid: (Constructor args invalid: (Kwargs 'icon' is invalid)))
```

I tried with this version too:
```rb
class IconComponentStories < ViewComponent::Storybook::Stories
  story :default do
    constructor({
      icon: text(:key)
    })
  end
end
```
Then rake task works, but Stories endpoint failed with the following error:
```
IconComponent: option 'icon' is required 
```

Maybe I missed something

**Comment by jonspalmer** [comment]
This is super helpful. I will experiment with this pattern. I'd be curious what are the parameters of the initializer for your IconComponent? what does this return?

```ruby
IconComponent.instance_method(:initialize).parameters
```

**Comment by nicolas-brousse** [comment]
I just ran this code in my rails console and I've got the following:

```irb
[1] pry(main)> IconComponent.instance_method(:initialize).parameters
=> [[:rest, :args]]
```

I guess `:args` come from [this code](https://github.com/dry-rb/dry-initializer/blob/8db20d810963f86915494e58bc12147e37955a64/lib/dry/initializer/mixin/root.rb#L6).

And maybe `:rest` come from `ruby2_keywords` 🤔 

Sorry, I would like to take more time digging into this to help you, but I've not enough time those days 😞

**Comment by jonspalmer** [comment]
Yup so the reason this works is that dry-initializer calls ruby2_keywords and as a result you can pass keyword args as "the last param" to the constructor. 

I suspect the right "fix" is to have a setting that can be turned on to allow that style which you would turn on when using dry-initializer. 

Also dry-initializer should fix things to be better behaved :)

**Comment by jonspalmer** [comment]
I'm pretty sure that this would fix the problem on the dry-initializer side :)

https://github.com/dry-rb/dry-initializer/pull/88

**Comment by jonspalmer** [comment]
A new version of dry-initializer changes the constructor and we expect this issue. https://github.com/dry-rb/dry-initializer/releases/tag/v3.1.0

Please test and confirm one way or the other.

**Comment by jonspalmer** [comment]
The dry-initializer change didn't do the trick but new changes in #112 should fix the issues with dry-initializer. Please test and confirm. I'll cut a release once others have validated.

**Comment by jonspalmer** [comment]
release v0.11.0 includes this fix for dry-initializer
