### ISSUE TITLE
Can't access webpacker assets in storybook UI

### ISSUE THREAD

**Issue by nicolas-brousse** [jonspalmer/view_component_storybook#18]
I try to use storybook on one of our projects.

I follow the README. But I have not the css loaded on my storybook.

All our css and js is configured with webpacker.

Versions:
```
view_component 2.22.1
view_component_storybook 0.4.0
```

```
@storybook/server@6.1.7
@storybook/addon-controls@6.1.7
```

Our custom layout:
```slim
doctype html
html lang=I18n.locale
  head
    title Stories
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_packs_with_chunks_tag "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_packs_with_chunks_tag "application", "data-turbolinks-track": "reload"

  body
    = yield
```

If I manually call an asset, I've got the following:

```
Cannot GET /packs/media/images/logo_sidebar-5d089ae2fbbd93e21cc4d54d342b72c6.png
```

For now the only solution I found is to force the `host` in `stylesheet_packs_with_chunks_tag` and `javascript_packs_with_chunks_tag` calls.

Is there a special configuration for that?

**Comment by jonspalmer** [comment]
I suspect the missing config is to set the asset_host which results in absolute paths vs relative paths in the stylesheet and javascript tags (which would not be unexpected in "production" with cdns etc. Something like this in `application.rb`

```ruby
conflig.application_controller.asset_host =  'http://localhost:3000'
```

Please report back if that works and we can add it to the Readme. Bonus points if you'd like to add the PR for Readme.md changes.

**Comment by miguelperez** [comment]
> I suspect the missing config is to set the asset_host which results in absolute paths vs relative paths in the stylesheet and javascript tags (which would not be unexpected in "production" with cdns etc. Something like this in `application.rb`
> 
> ```ruby
> conflig.application_controller.asset_host =  'http://localhost:3000'
> ```
> 
> Please report back if that works and we can add it to the Readme. Bonus points if you'd like to add the PR for Readme.md changes.

Just and FYI that this worked for me, but the correct config name in my case was:

```ruby
config.action_controller.asset_host =  'http://localhost:3000'
```
