### ISSUE TITLE
Components that use asset_path('asset name here') will try to get the assets from localhost:6006 instead of the rails app.

### ISSUE THREAD

**Issue by miguelperez** [jonspalmer/view_component_storybook#25]
Hi, first of all thanks for what you have done with supporting view_components on storybook!!! 🎉 .

Now onto my questions/issues: I have components that use SVG icons like this:

```ruby
= content_tag(:svg, @options) do
  use xlink:href="#{asset_url('icons/icons.svg')}##{@id}"
```

They work when using the application normally, since the helper correctly appends the host and port of the application.

When browsing those components in StoryBook, those assets are not displayed, looking at the browser console I noticed that the assets are being loaded from http://localhost:6006/assets. Port 6006 instead of 3000 or whatever port the rails app is running from.

I tried fixing the host on the call to asset_url to :3000 but then there is an error since the iframe under port 6006 is trying to access assets from localhost:3000:

> Unsafe attempt to load URL http://localhost:3000/assets/icons/icons-6e468b4eba233466beee0ed25e4c55850994879625e06d93917bdab59b1c2aa3.svg from frame with URL http://localhost:6006/iframe.html?id=button-component--with-short-text&viewMode=story. Domains, protocols and ports must match.

None of the assets images, pngs are loaded.

To load the stylesheets of the main app I used added the file ` .storybook/preview-head.html` with the content below following the advice here:  https://storybook.js.org/docs/react/configure/story-rendering#adding-to-head  and it worked!.

```html
<!-- .storybook/preview-head.html -->

<link rel="stylesheet" media="all" href="http://localhost:3000/assets/application.css">
<!-- Or you can load custom head-tag JavaScript: -->
<script src="http://localhost:3000/assets/application.js"></script>
```

Can you think of a workaround for the assets issue?

**Comment by jonspalmer** [comment]
Thanks for the kinds words.

This sounds a lot like the same problem as #18. I'd suggest making the config change suggested here: https://github.com/jonspalmer/view_component_storybook/issues/18#issuecomment-770232258

**Comment by miguelperez** [comment]
Thanks @jonspalmer for your reply. I tried that and it worked, in the sense that the assets are served now from the correct port. Also, the JS and Stylesheets are properly loaded.

But I am still getting the issue of

```js
Unsafe attempt to load URL http://localhost:3000/assets/icons/icons-6e468b4eba233466beee0ed25e4c55850994879625e06d93917bdab59b1c2aa3.svg from frame with URL http://localhost:6006/iframe.html?id=button-component--with-short-text&viewMode=story. Domains, protocols and ports must match.
```

On a side note, the config that I had to add to the app because it is rails 6 was:

```ruby
config.action_controller.asset_host =  'http://localhost:3000'
```

I will close this issue, since I think the safe unload problem might be related to SVG and localhost rather than to storybook or rails. If I find it to be something related I will open it again.

Thanks again!!!

**Comment by jonspalmer** [comment]
Great news. The "Unsafe attempt" warning is likely CORS settings. You can configure the Rack::Cors middleware a few different ways depending on your use case. I would expect that so solve the problem.

**Comment by miguelperez** [comment]
Thanks again, I will have a look at that and let you know how it goes.
