### ISSUE TITLE
Story book with content areas

### ISSUE THREAD

**Issue by SimonBo** [jonspalmer/view_component_storybook#28]
Are components using `with_content_areas` supported? How to write a basic story book for such components?

**Comment by jonspalmer** [comment]
I'm not sure we've spent much time on it yet but it would be good to support (or perhaps slots?) How might you think it should work?

**Comment by hjhart** [comment]
No movement on this issue in a few months. This can probably be closed until more interest is noted.

**Comment by dkniffin** [comment]
`with_content_area` was deprecated in `2.30.0`, in favor of slots. So we can probably close this issue in favor of reopening #11

**Comment by jonspalmer** [comment]
See #48 for further conversation on the right API for slots
