### ISSUE TITLE
Rendering with or without VC monkey-patch

### ISSUE THREAD

**Issue by Matt-Yorkley** [jonspalmer/view_component_storybook#30]
Hi, I'm playing with `view_component_storybook` in a Rails 5 app that uses the `wicked_pdf` gem and hitting the [clashing-monkey-patches issue](https://github.com/github/view_component/issues/288) with ViewComponent.

Would it make sense to replace `#render` here with `#render_component` to allow Storybook to work correctly regardless of whether the VC monkey patch is enabled or disabled?

https://github.com/jonspalmer/view_component_storybook/blob/baabed807adcb6d51f59f43cbf19db76bdf5a5ee/app/views/view_component/storybook/stories/show.html.erb#L1

Rails 5 compatibility notes [here](https://github.com/github/view_component/blob/a95fb2a9ebdd3cac93444ada9d8687e3c07c0edc/docs/compatibility.md) for reference.

**Comment by jonspalmer** [comment]
I'm not sure its quite as simple as that. We'd likely need to detect the monkey patch setting in ViewComponent and do the right thing. Happy to consider a pull request.

**Comment by Matt-Yorkley** [comment]
Ah! I thought the `#render_component` method was available either way, but yeah I see now it's only conditionally included after a Rails version check [here](https://github.com/github/view_component/blob/9ff88cd547b030730a22d0918f261b87ea7f2403/lib/view_component/engine.rb#L74).

**Comment by jonspalmer** [comment]
@Matt-Yorkley Can we close this?
