### ISSUE TITLE
Stubbing or accessing helpers in storybook

### ISSUE THREAD

**Issue by hjhart** [jonspalmer/view_component_storybook#44]
In the code below, the methods `current_user` would all error out, because they're not provided to controller that is handling requests from storybook.

It might be helpful to inject helper methods or variables into the  ViewComponent::Storybook::StoriesController as some sort of stub. Looking at the code, it doesn't appear to be something we can do. 

Should I write some sort of monkey patch to do this? Or would y'all be welcoming a pull request to potentially solve this problem. 

```
  class ContentCard < ViewComponent::Base
    attr_reader :content_id
    delegate :styles, :current_user, to: :helpers

    def initialize(content_id:)
      @content_id = content_id
    end

    def favorite_id
      return nil unless current_user
      content.favorite_id(current_user)
    end
  end
```

**Comment by hjhart** [comment]
Just a thought on implementation: 

```
    story(:default) do
      helpers do
        # Setting methods on the helper goes here
        Struct.new(current_user: User.new)
      end

      controls do
        select(:content_id, Content.all.pluck(:ids).map(&:to_s), Content.all.pluck(:id).sample.id.to_s)
      end

      content do
        "This is a test"
      end
    end
```

**Comment by jonspalmer** [comment]
@hjhart The example you give around accessing `current_user` from helpers is something of an anti-pattern for ViewComponents. It's common in VC to access helpers for thinks like rendering html (ie not helpers that contain state). However, if your component needs a user you should pass it in as a constructor parameter. That results in a more flexible component and also makes the component much more testable and as you discovered here easier to write stories around.

**Comment by hjhart** [comment]
Okay, nice. 

If I wanted to pass in a user object (or any non-primitive object to a Component) to a storybook story in this case, how would I do so?

Is there something in the Stories::DSL that would allow me to definine constructor parameters other than controls? I feel like I'm missing something important but haven't seen it in the documentation.

**Comment by strika** [comment]
I'm also interested in this question.

As far as I can tell, there's no way to pass an object (e.g. a model instance) to a component via a story. There is the [`object`](https://github.com/jonspalmer/view_component_storybook/blob/a2f90614f8622666812ea9e1efc3aa277c6b0d70/lib/view_component/storybook/dsl/controls_dsl.rb#L34-L36) control, but, the "object" is actually a Hash.

So, it seems to me that the only way to do this is to work with Hashes or to serialize data to a Hash (JSON) in a story and then deserialize that in the component. Is that correct?

**Comment by hjhart** [comment]
Update: @jonspalmer has proposed a new API to support this feature. 

https://github.com/jonspalmer/view_component_storybook/discussions/50

**Comment by jonspalmer** [comment]
I believe all the necessary fixes for this are now in main via the `custom` control. It requires upgrading to the new `constructor` api over the new deprecated `controls` api
