### ISSUE TITLE
Storybook Documentation?

### ISSUE THREAD

**Issue by hjhart** [jonspalmer/view_component_storybook#81]
Hello! It appears that the refactor to the README has obscured all the documentation that we had built (or maybe I'm missing something).

The documentation links to `https://viewcomponent.org/` but I don't see anything there about storybook. Is there another URL we meant to link to? Is it somewhere on that site that I'm missing?

Happy to submit a PR, too. 

As an aside, I'd be happy to throw some compilation step inside of GitHub Actions to generate and publish the docs.

**Comment by jonspalmer** [comment]
Fixed here a39ecce1c27625d14

I don't think publishing steps in Actions is necessary these days. It "just works".

**Comment by hjhart** [comment]
Amazing, thanks @jonspalmer.
