### ISSUE TITLE
Story arguments server serialization

### ISSUE THREAD

**Issue by fedegl** [jonspalmer/view_component_storybook#89]
When defining a story with array arguments, the parameters sent to the server are not properly serialized.

With the following story definition:
```rb
story :default do
  constructor(records: array([{ name: 'Name 1', amount: 1 }]))
end
```

I get something like this on the server:

```
Parameters: {"measureEnabled"=>"false", "outline"=>"false", "records"=>"[object Object]" }
```

I tried overwriting the `fetchStoryHtml` function, but the parameters received by it are already serialized. By looking at the code it seems that we need a way to override the **buildStoryArgs** function: https://github.com/storybookjs/storybook/blob/a8db9585f07d8cfc7354e68f6b780a6ff6536b38/app/server/src/client/preview/render.ts#L18 But there doesn't seem to be a way to override it.

Any suggestions are very much appreciated. And thanks for the amazing work :)

**Comment by jonspalmer** [comment]
See the linked PR - `array` becomes and alias for `object` which supports this use case already.
